
zuul:
  host:
    connect-timeout-millis: 4000
    socket-timeout-mills: 4000
  #设置所有的服务都不使用默认的反向代理
  ignored-services: '*'
  #/actuator/routes?format=detail
  prefix: /api
  routes:
    #单独设置某个服务的反向代理规则
    badou-cloud-consumer: /consumer/**
    badou-cloud-producer: /producer/**