spring:
  application:
    name: badou-cloud-eureka
  security:
    user:
      name: william
      password: godson
  profiles:
    active: es1

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    
server:
  port: 6781
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    httptrace:
      enabled: true
---
spring:
  profiles: es1
eureka:
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    prefer-ip-address: true
  server:
    enable-self-preservation: true
    #eviction-interval-timer-in-ms: 10000
    # 自我保护的阙值
    renewal-percent-threshold: 0.85
    # 阈值更新的时间间隔，默认是15分钟
    renewal-threshold-update-interval-ms: 900000
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://william:godson@192.168.0.201:${server.port}/eureka/,http://william:godson@192.168.0.202:${server.port}/eureka/
      
---
spring:
  profiles: es2
eureka:
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    prefer-ip-address: true
  server:
    enable-self-preservation: true
    #eviction-interval-timer-in-ms: 10000
    # 自我保护的阙值
    renewal-percent-threshold: 0.85
    # 阈值更新的时间间隔，默认是15分钟
    renewal-threshold-update-interval-ms: 900000
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://william:godson@192.168.0.200:${server.port}/eureka/,http://william:godson@192.168.0.202:${server.port}/eureka/

---
spring:
  profiles: es3
eureka:
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    prefer-ip-address: true
  server:
    enable-self-preservation: true
    #eviction-interval-timer-in-ms: 10000
    # 自我保护的阙值
    renewal-percent-threshold: 0.85
    # 阈值更新的时间间隔，默认是15分钟
    renewal-threshold-update-interval-ms: 900000
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://william:godson@192.168.0.201:${server.port}/eureka/,http://william:godson@192.168.0.200:${server.port}/eureka/
      
