
server:
  port: 8100

feign:
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000
  
spring:
  application:
    name: badou-consul-order
  cloud:
    consul:
      host: 192.168.0.200
      #host: 127.0.0.1
      port: 8500
      enabled: true
      discovery:
        # 官方推荐写方法，确保不重复
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        # 这个必须有，否则使用的是主机名而不是真实IP，会导致无法找到服务、健康检查失败
        prefer-ip-address: true
        tags: version=1.0,author=william,mail=suzq1981@qq.com
        # 这个必须配置正确，否则会导致无法健康检查，consul认为服务不正常
        health-check-path: /actuator/health
        # 心跳检查频率
        health-check-interval: 30s
        # 心跳检查超时时间
        health-check-timeout: 60s
        # 是否跳过证书检查
        health-check-tls-skip-verify: true
        #是否将自己注册到Consul
        register: true
        