server:
  port: 1000

spring:
  application:
    name: badou-cloud-config
  security:
    user:
      name: william
      password: godson
  cloud:
    config:
      enabled: true
      label: main
      server:
        git:
          uri: https://github.com/suzq1981/config.git
          search-paths: 
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    httptrace:
      enabled: true  

eureka:
  instance:
    app-group-name: config-group
    appname: ${spring.application.name}
    prefer-ip-address: true
    #续约时间间隔，默认30秒
    lease-renewal-interval-in-seconds: 30
    #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    lease-expiration-duration-in-seconds: 90
    metadata-map:
      cookie-time: 60s
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://william:godson@192.168.0.200:6781/eureka/,http://william:godson@192.168.0.201:6781/eureka/,http://william:godson@192.168.0.202:6781/eureka/
      defaultZone: http://william:godson@192.168.0.200:6781/eureka/
